version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 ls "s3://codepipeline-us-east-1-700038567080/GithubToS3Bucket"
     - aws s3 sync . "s3://codepipeline-us-east-1-700038567080/GithubToS3Bucket" --delete
 post_build:
   commands:
     - echo "post_build step"